# Generated by Django 5.0.9 on 2025-11-03 05:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch Category',
                'verbose_name_plural': 'Branch Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConcernCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concern Category',
                'verbose_name_plural': 'Concern Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('currency', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3)),
                ('phone_code', models.CharField(default='+91', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateUTMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_union_territory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'State/UT',
                'verbose_name_plural': 'States/UTs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type of Organization',
                'verbose_name_plural': 'Types of Organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('pan_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('msme_udyam_reg_no', models.CharField(blank=True, max_length=25)),
                ('tan_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid TAN format', regex='^[A-Z]{4}[0-9]{5}[A-Z]{1}$')])),
                ('cin_number', models.CharField(blank=True, max_length=21, validators=[django.core.validators.RegexValidator(message='Invalid CIN format', regex='^[A-Z]{1}[0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$')])),
                ('ie_code', models.CharField(blank=True, max_length=10)),
                ('exemption_certificates', models.TextField(blank=True)),
                ('billing_currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('AED', 'UAE Dirham (AED)')], default='INR', max_length=3)),
                ('payment_terms', models.CharField(choices=[('net_7', 'Net 7 Days'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_45', 'Net 45 Days'), ('net_60', 'Net 60 Days'), ('due_on_receipt', 'Due on Receipt'), ('advance', 'Advance Payment')], default='net_30', max_length=20)),
                ('requires_advance', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('website', models.URLField(blank=True)),
                ('billing_contact_person', models.CharField(blank=True, max_length=100)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('billing_contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CMS.typeoforganization')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('gst_certificate', 'GST Certificate'), ('msme_certificate', 'MSME Certificate'), ('incorporation_certificate', 'Incorporation Certificate'), ('trade_license', 'Trade License'), ('udyam_certificate', 'Udyam Certificate'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='customer_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='CMS.customermaster')),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='CMS.customermaster')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Note',
                'verbose_name_plural': 'Customer Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_category', models.CharField(choices=[('registered_office', 'Registered Office/Head Office'), ('branch_office', 'Regional/Branch Office'), ('factory', 'Factory/Mfg. Facility'), ('warehouse', 'Godown/Warehouse'), ('project_site', 'Job Site/Project Site')], max_length=20)),
                ('branch_id', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('google_location', models.CharField(blank=True, max_length=300)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid GST format', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CMS.countrymaster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='CMS.customermaster')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CMS.stateutmaster')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_primary', 'branch_category'],
                'unique_together': {('customer', 'branch_id')},
            },
        ),
        migrations.CreateModel(
            name='CustomerConcernPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_category', models.CharField(blank=True, choices=[('registered_office', 'Registered Office/Head Office'), ('branch_office', 'Regional/Branch Office'), ('factory', 'Factory/Mfg. Facility'), ('warehouse', 'Godown/Warehouse'), ('project_site', 'Job Site/Project Site')], max_length=20)),
                ('concern_person', models.CharField(max_length=240)),
                ('designation', models.CharField(blank=True, max_length=240)),
                ('mobile_1', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^[0-9]{10}$')])),
                ('mobile_2', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^[0-9]{10}$')])),
                ('office_phone_1', models.CharField(blank=True, max_length=11)),
                ('office_extension_1', models.CharField(blank=True, max_length=4)),
                ('office_phone_2', models.CharField(blank=True, max_length=11)),
                ('email_company', models.EmailField(blank=True, max_length=254)),
                ('email_personal', models.EmailField(blank=True, max_length=254)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_persons', to='CMS.customeraddress')),
                ('concern_for', models.ManyToManyField(blank=True, related_name='concern_persons', to='CMS.concerncategory')),
                ('country_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concern_persons_country1', to='CMS.countrymaster')),
                ('country_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concern_persons_country2', to='CMS.countrymaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_concern_persons', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_persons', to='CMS.customermaster')),
            ],
            options={
                'verbose_name': 'Customer Concern Person',
                'verbose_name_plural': 'Customer Concern Persons',
                'ordering': ['customer', 'concern_person'],
                'indexes': [models.Index(fields=['concern_person'], name='CMS_custome_concern_4e4bbc_idx'), models.Index(fields=['is_active'], name='CMS_custome_is_acti_74022c_idx'), models.Index(fields=['customer', 'is_active'], name='CMS_custome_custome_fc8810_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code format', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('cc', 'Cash Credit'), ('od', 'Overdraft')], default='current', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='CMS.customermaster')),
            ],
            options={
                'verbose_name': 'Customer Bank Detail',
                'verbose_name_plural': 'Customer Bank Details',
                'ordering': ['-is_primary', 'bank_name'],
                'unique_together': {('customer', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='CMS.customermaster')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.divisionmaster')),
            ],
            options={
                'verbose_name': 'Customer Division',
                'verbose_name_plural': 'Customer Divisions',
                'unique_together': {('customer', 'division')},
            },
        ),
        migrations.AddIndex(
            model_name='customermaster',
            index=models.Index(fields=['name'], name='CMS_custome_name_c21480_idx'),
        ),
        migrations.AddIndex(
            model_name='customermaster',
            index=models.Index(fields=['customer_id'], name='CMS_custome_custome_8cd73a_idx'),
        ),
        migrations.AddIndex(
            model_name='customermaster',
            index=models.Index(fields=['pan_number'], name='CMS_custome_pan_num_a832b3_idx'),
        ),
        migrations.AddIndex(
            model_name='customermaster',
            index=models.Index(fields=['is_active'], name='CMS_custome_is_acti_b579e5_idx'),
        ),
    ]
