# Generated by Django 5.0.9 on 2025-10-31 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='document_master',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.TextField(blank=True, null=True)),
                ('doc_subpath', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('mandatory', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'document_master',
            },
        ),
        migrations.CreateModel(
            name='status_color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status_color',
            },
        ),
        migrations.CreateModel(
            name='status_master',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField(blank=True, null=True)),
                ('status_type', models.TextField(blank=True, null=True)),
                ('status_color', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('level', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.CreateModel(
            name='application_search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.TextField(blank=True, null=True)),
                ('menu_id', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_search_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_search_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_search',
            },
        ),
        migrations.CreateModel(
            name='parameter_master',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.TextField(blank=True, null=True)),
                ('parameter_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parameter_master',
            },
        ),
    ]
