# Generated by Django 5.0.9 on 2025-11-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='approval_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='blacklist_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='msme_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='msme_type',
            field=models.CharField(blank=True, choices=[('M', 'Micro'), ('S', 'Small'), ('D', 'Medium'), ('G', 'General'), ('T', 'Not Applicable')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_preference',
            field=models.CharField(blank=True, choices=[('cash', 'By Cash'), ('cheque', 'By Cheque'), ('dd', 'By Demand Draft'), ('rtgs', 'By RTGS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='registered_with_bluechip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='responsibility_return_replace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_group',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='work_description',
            field=models.CharField(blank=True, choices=[('material_supplier', 'Material Supplier'), ('service_provider', 'Service Provider'), ('labour_supplier', 'Labour Supplier'), ('general_contractor', 'General Contractor')], max_length=20, null=True),
        ),
    ]
