# Generated by Django 5.0.9 on 2025-11-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_blacklisted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='registered_with_bluechip',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='responsibility_return_replace',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
