# Generated by Django 5.0.9 on 2025-11-03 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_is_blacklisted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorapprovallog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('cc', 'Cash Credit'), ('od', 'Overdraft')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='bankers_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='iban_code',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='is_primary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='micr_code',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Enter a valid MICR code')]),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='swift_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorconcernperson',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorconcernperson',
            name='designation',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='vendorconcernperson',
            name='is_primary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendorconcernperson',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[6-9][0-9]{9}$', 'Enter a valid mobile number')]),
        ),
        migrations.AlterField(
            model_name='vendorconcernperson',
            name='office_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,12}$', 'Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='vendorconcernperson',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='fax',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,12}$', 'Enter a valid fax number')]),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='is_primary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='others_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='others_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='quality_engineers_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='quality_engineers_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='resident_managers_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='resident_managers_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='safety_coordinators_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='safety_coordinators_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='site_engineers_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='site_engineers_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='skilled_workmen_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='skilled_workmen_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='supervisors_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='supervisors_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorreference',
            name='ex_scip_employee_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorreference',
            name='ex_scip_employee_designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorreference',
            name='ex_scip_employee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorreference',
            name='scip_employee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorreference',
            name='scip_employee_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsisterconcern',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsisterconcern',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsisterconcern',
            name='fax',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,12}$', 'Enter a valid fax number')]),
        ),
        migrations.AlterField(
            model_name='vendorsisterconcern',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsisterconcern',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorstatutory',
            name='cpwd_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorstatutory',
            name='cpwd_registered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendorstatutory',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Enter a valid GST number')]),
        ),
        migrations.AlterField(
            model_name='vendorstatutory',
            name='pf_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorstatutory',
            name='service_tax_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorstatutory',
            name='vat_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
