# Generated by Django 5.0.9 on 2025-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendorapprovallog_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontact',
            name='working_time_from',
            field=models.TimeField(default='10:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='working_time_to',
            field=models.TimeField(default='19:00:00', null=True),
        ),
    ]
