# Generated by Django 5.0.9 on 2025-11-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorcontact_working_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontact',
            name='weekly_holidays',
            field=models.JSONField(default=list, null=True),
        ),
    ]
