# Generated by Django 5.0.9 on 2025-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendorcontact_weekly_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormanpower',
            name='others',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='quality_engineers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='resident_managers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='safety_coordinators',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='site_engineers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='skilled_workmen',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanpower',
            name='supervisors',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
