# Generated by Django 5.0.9 on 2025-11-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendormanpower_others_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/%Y/%m/'),
        ),
    ]
